services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: halil
      POSTGRES_PASSWORD: 123
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    container_name: django_app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      
volumes:
  dbdata:
