
### CREATE USER 1 
POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "okidoki", "password": "oktay1234", "email": "oktay@mail.com" }

### CREATE USER 2

POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "halilozky", "password": "halil1234", "email": "halil@mail.com" }

### FALSE LOGIN REQUEST 
POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "oktay", "password": "oktay1234" }

### CORRECT LOGIN REQUEST

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "okidoki", "password": "oktay1234" }
