# Generated by Django 5.0.4 on 2024-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_searchresult_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchresult",
            name="image",
            field=models.TextField(),
        ),
    ]
