# Generated by Django 5.0.4 on 2024-05-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_searchresult_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchresult",
            name="description",
        ),
    ]
