export { default as Home } from './Home'
export { default as Feed } from './Feed'
export { default as Profile } from './Profile'
export { default as Architect } from './Architect'
export { default as Building } from './Building'
export { default as Style } from './Style'
