# Generated by Django 4.2.16 on 2024-11-22 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionprogress',
            unique_together={('question', 'user')},
        ),
    ]
