# Generated by Django 4.2.16 on 2024-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(default='eng', max_length=10000),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
