# Generated by Django 4.2.17 on 2024-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wordbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbookmark',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
