# Generated by Django 4.2.16 on 2024-11-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_bookmarked_by_alter_bookmark_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
    ]
