# Generated by Django 4.2.16 on 2024-11-23 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
