# Generated by Django 4.2.16 on 2024-10-26 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tags_remove_quiz_level_quiz_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='posts', to='app.tags')),
            ],
        ),
    ]
