# Generated by Django 4.2.17 on 2024-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='object_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
