# Generated by Django 4.2.16 on 2024-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_word_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
