# Generated by Django 4.2.16 on 2024-10-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_word_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='Meaning not available', max_length=1000),
        ),
    ]
