# Generated by Django 4.2.16 on 2024-11-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_translation_remove_word_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.CharField(default='Sentence not available', max_length=1000),
        ),
    ]
